before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    binary: doppler
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    - goos: darwin
      goarch: "386"
    - goos: windows
      goarch: "386"
    - goos: freebsd
      goarch: "386"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

release:
  github:
    owner: DopplerHQ
    name: cli

checksum:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum
  - args:
    - "-u"
    - "B70BD7FCA460C4A3D0EEB965D3D593D50EE79DEC"
    - "--output"
    - "${signature}"
    - "--detach-sign"
    - "${artifact}"

snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - name: doppler
    github:
      owner: DopplerHQ
      name: homebrew-tap
    commit_author:
      name: "Doppler Bot"
      email: support@doppler.com
    folder: Formula
    homepage: "https://doppler.com"
    description: "The official Doppler CLI for managing your secrets and config"

scoop:
  bucket:
    owner: DopplerHQ
    name: scoop-bucket
  commit_author:
    name: "Doppler Bot"
    email: support@doppler.com
  homepage: "https://doppler.com"
  description: "The official Doppler CLI for managing your secrets and config"
  license: Apache-2.0

snapcrafts:
  - name: doppler
    id: doppler
    base: core18
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Linux
    summary: "The official Doppler CLI"
    description: "Doppler helps you manage your secrets and config across all your projects."
    license: Apache-2.0
    plugs:
      personal-files:
        read:
          - $HOME/.doppler.json
        write:
          - $HOME/.config/.doppler.yaml
