project_name: cli

before:
  hooks:
    - go mod tidy

builds:
  -
    binary: doppler
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    - goos: darwin
      goarch: "386"
    - goos: windows
      goarch: "386"
    - goos: freebsd
      goarch: "386"

archives:
-
  replacements:
    darwin: macOS
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

release:
  github:
    owner: DopplerHQ
    name: cli

checksum:
  name_template: 'checksums.txt'

signs:
  -
    artifacts: checksum
    args:
      - "-u"
      - "B70BD7FCA460C4A3D0EEB965D3D593D50EE79DEC"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
  -
    binaries:
      - cli
    image_templates:
      - "DopplerHQ/cli:latest"
      - "DopplerHQ/cli:{{ .Tag }}"                  # Ex: v1.4.2
      - "DopplerHQ/cli:v{{ .Major }}"               # Ex: v1
      - "DopplerHQ/cli:v{{ .Major }}.{{ .Minor }}"  # Ex: v1.4
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"

brews:
  - name: doppler
    github:
      owner: DopplerHQ
      name: homebrew-cli
    commit_author:
      name: "Doppler Bot"
      email: support@doppler.com
    folder: Formula
    homepage: "https://doppler.com"
    description: "The official Doppler CLI for managing your secrets and config"

scoop:
  bucket:
    owner: DopplerHQ
    name: scoop-cli
  commit_author:
    name: "Doppler Bot"
    email: support@doppler.com
  homepage: "https://doppler.com"
  description: "The official Doppler CLI for managing your secrets and config"
  license: Apache-2.0

snapcrafts:
  - name: doppler
    id: doppler
    base: core18
    replacements:
      darwin: macOS
      386: i386
      amd64: x86_64
    summary: "The official Doppler CLI"
    description: "Doppler helps you manage your secrets and config across all your projects."
    license: Apache-2.0
    plugs:
      personal-files:
        read:
          - $HOME/.doppler.json
        write:
          - $HOME/.config/.doppler.yaml

nfpms:
  - id: cli
    replacements:
      386: i386
      amd64: x86_64
    homepage: "https://doppler.com"
    maintainer: Doppler Bot <support@doppler.com>
    description: "The official Doppler CLI for managing your secrets and config"
    license: Apache-2.0
    formats:
      - deb
      - rpm
