project_name: cli

before:
  hooks:
    - go mod tidy
    - echo $(doppler secrets get GOOGLE_APPLICATION_CREDENTIALS_CONTENT --plain) > $(doppler secrets get GOOGLE_APPLICATION_CREDENTIALS --plain)

builds:
  -
    binary: doppler
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    - goos: darwin
      goarch: "386"
    - goos: windows
      goarch: "386"
    - goos: freebsd
      goarch: "386"
    ldflags:
      - -s -w -X github.com/DopplerHQ/cli/version.ProgramVersion=v{{.Version}}

archives:
-
  replacements:
    darwin: macOS
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

release:
  github:
    owner: DopplerHQ
    name: cli

checksum:
  name_template: 'checksums.txt'

signs:
  -
    artifacts: checksum
    args:
      - "-u"
      - "B70BD7FCA460C4A3D0EEB965D3D593D50EE79DEC"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'

dockers:
  - dockerfile: docker/alpine
    goos: linux
    goarch: amd64
    binaries:
      - doppler
    image_templates:
      - "dopplerhq/cli:{{ .Version }}"             # Ex: 1.4.2
      - "dopplerhq/cli:{{ .Major }}.{{ .Minor }}"  # Ex: 1.4
      - "dopplerhq/cli:{{ .Major }}"               # Ex: 1
      - "dopplerhq/cli:latest"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  - dockerfile: docker/node:alpine
    goos: linux
    goarch: amd64
    binaries:
      - doppler
    image_templates:
      - "dopplerhq/cli:{{ .Version }}-node"             # Ex: 1.4.2
      - "dopplerhq/cli:{{ .Major }}.{{ .Minor }}-node"  # Ex: 1.4
      - "dopplerhq/cli:{{ .Major }}-node"               # Ex: 1
      - "dopplerhq/cli:node"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"

brews:
  - name: doppler
    github:
      owner: DopplerHQ
      name: homebrew-cli
    commit_author:
      name: "Doppler Bot"
      email: support@doppler.com
    folder: Formula
    homepage: "https://doppler.com"
    description: "The official Doppler CLI for managing your secrets and config"

scoop:
  bucket:
    owner: DopplerHQ
    name: scoop-cli
  commit_author:
    name: "Doppler Bot"
    email: support@doppler.com
  homepage: "https://doppler.com"
  description: "The official Doppler CLI for managing your secrets and config"
  license: Apache-2.0

snapcrafts:
  - name: doppler
    id: doppler
    base: core18
    replacements:
      darwin: macOS
      386: i386
      amd64: x86_64
    summary: "The official Doppler CLI"
    description: "Doppler helps you manage your secrets and config across all your projects."
    license: Apache-2.0
    plugs:
      personal-files:
        read:
          - $HOME/.doppler.json
        write:
          - $HOME/.config/.doppler.yaml

nfpms:
  - id: cli
    replacements:
      386: i386
      amd64: x86_64
    homepage: "https://doppler.com"
    maintainer: Doppler Bot <support@doppler.com>
    description: "The official Doppler CLI for managing your secrets and config"
    license: Apache-2.0
    formats:
      - deb
      - rpm

blobs:
  -
    provider: gs
    bucket: dopplerhq_cli_releases
    folder: "{{ .Tag }}"
