# before:
#   hooks:
#     # you may remove this if you don't use vgo
#     - go mod tidy
#     # you may remove this if you don't need go generate
#     - go generate ./...
builds:
  - id: doppler-cli
    binary: doppler
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - dragonfly
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  # name_template: "{{ .Tag }}-next"
  name_template: "SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
