name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Checkout
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Build
      run: go build
      env:
        GOPATH: ${{ runner.workspace }}
    - name: Test
      run: make test
      env:
        GOPATH: ${{ runner.workspace }}
    - name: GoReleaser Check
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: check
      env:
        GOPATH: ${{ runner.workspace }}
