name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@master
    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v1
      with:
        args: --snapshot --skip-publish
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#     - name: Go Release Binary
#       uses: ngs/go-release.action@v1.0.0
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
