name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - name: Checkout
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Fetch dependencies
      run: cd ${{ runner.workspace }}/src/github.com/${{ github.repository }} && go get
      env:
        GOPATH: ${{ runner.workspace }}
    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --snapshot --skip-publish
      env:
        GOPATH: ${{ runner.workspace }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: Go Release Binary
#       uses: ngs/go-release.action@v1.0.0
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
