name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: GoReleaser Action
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      uses: goreleaser/goreleaser-action@v0.1.0
      with:
        args: --snapshot --skip-publish
#     - name: Go Release Binary
#       uses: ngs/go-release.action@v1.0.0
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
