name: release

on:
  workflow_dispatch:
    inputs:
      type:
        description: How the new release should be versioned
        required: true
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.18'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: "master"
    - name: Update alpine image
      run: docker pull alpine
    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v1
    - name: Install Cloudsmith CLI
      run: pip install --upgrade cloudsmith-cli

    # TODO install docker, gpg, goreleaser
    - name: Build binaries
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --snapshot --skip-publish --skip-sign
      env:
        GOPATH: ${{ runner.workspace }}
